import { type RouterOutputs, api } from "~/utils/api";
import { SignInButton, useUser } from "@clerk/nextjs";

import Head from "next/head";
import Image from "next/image";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { Loading } from "~/components/loading";
dayjs.extend(relativeTime);

type PostWithUser = RouterOutputs["post"]["getAll"][number];

function PostView({ post, author }: PostWithUser) {
  return (
    <div className="flex gap-3 border-b border-slate-400 p-4">
      <Image
        className="h-14 w-14 rounded-full"
        width={56}
        height={56}
        src={author.imageUrl}
        alt={author.username}
      />
      <div className="flex flex-col">
        <div className="flex gap-1 text-slate-300">
          <span>@{author.username}</span>
          <span>·</span>
          <span className="font-thin">{dayjs(post.createdAt).fromNow()}</span>
        </div>
        <span className="text-2xl">{post.content}</span>
      </div>
    </div>
  );
}

function CreatePostWizard() {
  const { user } = useUser();
  console.log(user);
  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <Image
        className="h-14 w-14 rounded-full"
        width={56}
        height={56}
        src={user.imageUrl}
        alt={user.username ?? ""}
      />
      <input
        placeholder="What's on your mind?"
        className="grow bg-transparent outline-none"
      />
    </div>
  );
}

function Feed() {
  const { data, isLoading: isPostsLoading } = api.post.getAll.useQuery();
  const postState = isPostsLoading ? "loading" : "loaded";

  if (postState === "loading") return <Loading />;

  if (!data) return <div>Error</div>;

  return (
    <div className="flex flex-col">
      {[...data, ...data].map((fullPost) => (
        <PostView {...fullPost} key={fullPost.post.id} />
      ))}
    </div>
  );
}

export default function Home() {
  const { isSignedIn, isLoaded } = useUser();
  //prefetching the post data
  api.post.getAll.useQuery();

  const userState = isLoaded
    ? isSignedIn
      ? "signed-in"
      : "signed-out"
    : "loading";

  // return empty div if user or post is loading, since  user tends to load faster than post
  if (userState === "loading") return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="h-screen w-full border-x border-slate-400 md:max-w-2xl">
          <div className="border-b border-slate-400 p-4">
            {userState === "signed-in" ? (
              <CreatePostWizard />
            ) : (
              <SignInButton />
            )}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
}
